enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[CamScanner]
patches-source = "hoo-dles/morphe-patches"
rv-brand = "hoo-dles"
arch = "arm64-v8a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"
enabled = false

[Duolingo]
patches-source = "hoo-dles/morphe-patches"
rv-brand = "hoo-dles"
arch = "arm64-v8a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
enabled = false

[Facebook]
patches-source = "RookieEnough/De-ReVanced"
rv-brand = "de-revanced"
arch = "arm64-v8a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
enabled = false

[FotMob]
patches-source = "hoo-dles/morphe-patches"
rv-brand = "hoo-dles"
arch = "arm64-v8a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/fotmob-as/fotmob-live-soccer-scores"
uptodown-dlurl = "https://soccer-scores.en.uptodown.com/android"
enabled = false

[GooglePhotos]
patches-source = "RookieEnough/De-ReVanced"
rv-brand = "de-revanced"
build-mode = "module"
arch = "arm64-v8a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Instagram]
patches-source = "crimera/piko"
rv-brand = "piko"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
enabled = false

[MoonReader]
patches-source = "binarymend/morphe-patches"
rv-brand = "binarymend"
arch = "arm64-v8a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/moon/moon-reader"
uptodown-dlurl = "https://moon-reader.en.uptodown.com/android"
enabled = false

[SolidExplorer]
patches-source = "hoo-dles/morphe-patches"
rv-brand = "hoo-dles"
arch = "arm64-v8a"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-file-manager"
uptodown-dlurl = "https://solid-explorer.en.uptodown.com/android"
enabled = false

[Threads]
patches-source = "RookieEnough/De-ReVanced"
rv-brand = "de-revanced"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app"
enabled = false
